In [1]:
import numpy as np
from PIL import Image 
import glob
image_list =[]
resized_image=[]

def upload_images():
    try:
        for file_name in glob.glob('Photos/*.jpg'):
            img=Image.open(file_name)
            image_list.append(img)
    except IOError:print ("Error: can't find file or read data")

def convert_img():
    try:
        for image in image_list:
            image=image.resize((200,200))
            resized_image.append(image)
    except ValueError as Argument:
        print ("The code does not contain \n", Argument)
        
def Save_img():
    try :
        for (i,new) in enumerate(resized_image):
            new.save('{}{}{}'.format('Saved_IMG',i+1,'.jpg'))
    except Exception as err:print("Erro {}".format(err))    
            
def img_to_array():
    try:
        for img1 in resized_image: 
            global new_image
            new_image =np.array(img1)
    except Exception as err:print("Erro {}".format(err))    
        
def main():
    upload_images()
    convert_img()
    Save_img()
    img_to_array()
    print("Array Shape = ",new_image.shape)
    print("Array Size = ",new_image.size)
    print("\n ",new_image[:,:,2])
    
if __name__=='__main__':
    main()

Array Shape =  (200, 200, 3)
Array Size =  120000

  [[132 134 129 ... 122 122 121]
 [130 130 130 ... 120 121 118]
 [130 133 135 ... 116 119 122]
 ...
 [ 70  61  49 ...  11 124   7]
 [ 36  51  56 ...  38  47  57]
 [ 95  70  58 ...  37   0  63]]
